[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
equxi = "9p47LiT9ondNZwhC1dqC6ChMTNr7mRLc3RGvi39JVemQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
